# Site
repository: a-silvia/a-silvia.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ana Silvia
title: Data Scientist

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  a-silvia
linkedin_username: anasilviacsilva
orcid_username: 0000-0003-2584-4034
googlescholar_username: QQzStGIAAAAJ


# About Section
about_title: about
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Data Scientist that has a hard time settling on one thing only. I have
  worked in academia and successfully defended my Ph.D. in 2019, in the lovely
  city of Ghent (Belgium). Afterwards I switched gears and opted for a career in
  industry, and in 2020 relocated to Porto, Portugal (yes, mid pandemic!). I
  love stubbornly (or, optimistically, preserverantly) riding my bike, picking
  up assorted hobbies, reading, cooking, playing videogames, boardgames and
  RPGs, and pretending my cats love me as much as I them!

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: FARFETCH
        sub_title: Data Scientist
        caption: September 2020 - present
        quote: >
          FARFETCH is the global platform for luxury fashion.
        description: |
          I have worked in the Experimentation team, supporting internal
          experiments (A/B tests and others) for about one and a half years.
          Since January 2022 I have been part of the Personalisation &
          Recommendations team, where we develop customer facing models and
          support other teams' personalisation efforts.
      - layout: right
        title: Crunch Analytics
        sub_title: Data Scientist
        caption: September 2019 - August 2020
        quote: >
            Crunch drives business impact by transforming the way organizations
            use their data.
        description: |
          At Crunch I participated in several different projects, developing
          my skills very broadly -- both in data engineering, data science and
           analytics, as well as providing training in the form of deep learning
          courses.
      - layout: right
        title: iCBR
        sub_title: Research Fellow - Data Scientist
        caption: September 2013 - October 2014
        quote: >
            iCBR (former IBILI) is a biomedical research institution connected
             to the University of Coimbra
        description: |
          At iCBR I was part of a research project where we aimed to
           preemptively identify patients at risk of developing an
           opththalmological condition, based on OCT scans and through machine
            learning
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Gent Universiteit
        sub_title: Ph. D.
        caption: 2014 -  2019
        description: |
          I developed data-driven tools to assist in the identification of
          mass spectrometry data in two different -omics settings: HR-MS2
          spectra in the context of proteomics, and MS images in the context of
           metabolomics. You can read my thesis [here](https://www.linkedin.com/in/anasilviacsilva/overlay/1557925045290/single-media-viewer/?type=DOCUMENT&profileId=ACoAAAXRp8kBXs56rcPWZZyOfUydq-RbIz5Xz38).

      - layout: top-right
        title: Universidade de Coimbra
        sub_title: M. Sc.
        caption: 2007 - 2013
        description: |
          I studied biomedical engineering with a specialisation in imaging and
          radiation. My MSc thesis was about simulating the propagation of light
           in a heterogeneous medium, from a finite differences implementation
           of Maxwell's equations. You can find a pdf of my thesis
           [here](https://estudogeral.sib.uc.pt/handle/10316/26779).
      - layout: top-right
        title: České vysoké učení technické v Praze
        sub_title: Erasmus
        caption: 2011
        description: |
          I spent one semester in Prague as part of the Erasmus exchange
          program.
  - title: A Little More About Me
    layout: text
    content: |
      I am the definition of a jack-of-all-trades, master-of-none when it comes
      to my interests & hobbies. I never tire of learning and experimenting new
       things! Sustainability and community building are very important to me.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
